# Generated by Django 5.0.6 on 2024-05-17 21:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
